// Semilla de RESPALDO del universo (solo si company_tickers.json cambia de forma o no responde):
// las mayores de EEUU con su nombre. Con la semilla el radar degrada a ~60 nombres y lo AVISA en la
// línea de salud — nunca falla en silencio. El universo normal (550) viene de la SEC en runtime.
export const UNIVERSO_SEMILLA: Array<{ simbolo: string; nombre: string }> = [
  { simbolo: 'AAPL', nombre: 'Apple Inc.' }, { simbolo: 'MSFT', nombre: 'Microsoft Corp' },
  { simbolo: 'NVDA', nombre: 'NVIDIA Corp' }, { simbolo: 'AMZN', nombre: 'Amazon.com Inc' },
  { simbolo: 'GOOG', nombre: 'Alphabet Inc' }, { simbolo: 'META', nombre: 'Meta Platforms Inc' },
  { simbolo: 'BRK.B', nombre: 'Berkshire Hathaway' }, { simbolo: 'AVGO', nombre: 'Broadcom Inc' },
  { simbolo: 'TSLA', nombre: 'Tesla Inc' }, { simbolo: 'LLY', nombre: 'Eli Lilly & Co' },
  { simbolo: 'JPM', nombre: 'JPMorgan Chase & Co' }, { simbolo: 'V', nombre: 'Visa Inc' },
  { simbolo: 'XOM', nombre: 'Exxon Mobil Corp' }, { simbolo: 'UNH', nombre: 'UnitedHealth Group' },
  { simbolo: 'MA', nombre: 'Mastercard Inc' }, { simbolo: 'PG', nombre: 'Procter & Gamble' },
  { simbolo: 'JNJ', nombre: 'Johnson & Johnson' }, { simbolo: 'COST', nombre: 'Costco Wholesale' },
  { simbolo: 'HD', nombre: 'Home Depot Inc' }, { simbolo: 'ABBV', nombre: 'AbbVie Inc' },
  { simbolo: 'WMT', nombre: 'Walmart Inc' }, { simbolo: 'NFLX', nombre: 'Netflix Inc' },
  { simbolo: 'BAC', nombre: 'Bank of America' }, { simbolo: 'CRM', nombre: 'Salesforce Inc' },
  { simbolo: 'ORCL', nombre: 'Oracle Corp' }, { simbolo: 'CVX', nombre: 'Chevron Corp' },
  { simbolo: 'KO', nombre: 'Coca-Cola Co' }, { simbolo: 'AMD', nombre: 'Advanced Micro Devices' },
  { simbolo: 'PEP', nombre: 'PepsiCo Inc' }, { simbolo: 'TMO', nombre: 'Thermo Fisher Scientific' },
  { simbolo: 'LIN', nombre: 'Linde plc' }, { simbolo: 'ADBE', nombre: 'Adobe Inc' },
  { simbolo: 'MCD', nombre: "McDonald's Corp" }, { simbolo: 'CSCO', nombre: 'Cisco Systems' },
  { simbolo: 'ACN', nombre: 'Accenture plc' }, { simbolo: 'ABT', nombre: 'Abbott Laboratories' },
  { simbolo: 'MRK', nombre: 'Merck & Co' }, { simbolo: 'INTU', nombre: 'Intuit Inc' },
  { simbolo: 'GE', nombre: 'GE Aerospace' }, { simbolo: 'DIS', nombre: 'Walt Disney Co' },
  { simbolo: 'PFE', nombre: 'Pfizer Inc' }, { simbolo: 'QCOM', nombre: 'Qualcomm Inc' },
  { simbolo: 'TXN', nombre: 'Texas Instruments' }, { simbolo: 'CAT', nombre: 'Caterpillar Inc' },
  { simbolo: 'VZ', nombre: 'Verizon Communications' }, { simbolo: 'IBM', nombre: 'IBM Corp' },
  { simbolo: 'AMGN', nombre: 'Amgen Inc' }, { simbolo: 'GS', nombre: 'Goldman Sachs Group' },
  { simbolo: 'NOW', nombre: 'ServiceNow Inc' }, { simbolo: 'ISRG', nombre: 'Intuitive Surgical' },
  { simbolo: 'SPGI', nombre: 'S&P Global Inc' }, { simbolo: 'UBER', nombre: 'Uber Technologies' },
  { simbolo: 'BKNG', nombre: 'Booking Holdings' }, { simbolo: 'HON', nombre: 'Honeywell International' },
  { simbolo: 'MS', nombre: 'Morgan Stanley' }, { simbolo: 'BLK', nombre: 'BlackRock Inc' },
  { simbolo: 'DE', nombre: 'Deere & Co' }, { simbolo: 'LMT', nombre: 'Lockheed Martin' },
  { simbolo: 'SBUX', nombre: 'Starbucks Corp' }, { simbolo: 'AXP', nombre: 'American Express' },
]
