'use client'
import { C, SE, SN, SM, SC } from '@/lib/colors'
import React, { useState, useEffect, useCallback, useRef } from 'react'
import { useAuth } from '@/hooks/useAuth'
import Analytics from '@/components/Analytics'
import AnalyticsComparativo from '@/components/owner/AnalyticsComparativo'
import SugerenciaButton from '@/components/SugerenciaButton'
import { HelpChat } from '@/components/help/HelpChat'
import { copyToClipboard } from '@/lib/clipboard'
import { supabase } from '@/lib/supabase'
import CartaPublicPanel from '@/components/owner/CartaPublicPanel'
import FueraCartaSection from '@/components/owner/FueraCartaSection'
import SupervisorTab from '@/components/owner/SupervisorTab'
import BridgeSetupWizard from '@/components/owner/BridgeSetupWizard'
import DiagnosticoTab from '@/components/owner/DiagnosticoTab'
import SoporteTab from '@/components/owner/SoporteTab'
import MensajesOwnerTab from '@/components/owner/MensajesOwnerTab'
import FichajesTab from '@/components/owner/FichajesTab'
import ModalTraducciones from '@/components/owner/ModalTraducciones'
import RecomendacionesTab from '@/components/owner/RecomendacionesTab'
import ManualVozTab from '@/components/owner/ManualVozTab'
import DashboardTab from '@/components/owner/DashboardTab'
import ForecasterTab from '@/components/owner/ForecasterTab'
import RRHHTab from '@/components/owner/RRHHTab'
import TiendaTab from '@/components/owner/TiendaTab'
import AnalisisCartaTab from '@/components/owner/AnalisisCartaTab'
import EtiquetasTab from '@/components/owner/EtiquetasTab'
import ProveedorFichaModal from '@/components/owner/ProveedorFichaModal'
import PagosProveedorTab from '@/components/owner/PagosProveedorTab'
import ContabilidadTab from '@/components/owner/ContabilidadTab'
import OwnerCopiloto from '@/components/owner/OwnerCopiloto'
import ModulosTab from '@/components/owner/ModulosTab'
import NuevaEntradaPesoModal from '@/components/owner/NuevaEntradaPesoModal'
import MiWebTab from '@/components/owner/MiWebTab'
import SmartScanFAB from '@/components/SmartScanFAB'
import WineScannerModal from '@/components/WineScannerModal'
import EventosTab from '@/components/owner/EventosTab'
import MenusEventoTab from '@/components/owner/MenusEventoTab'
import CRMEventosTab from '@/components/owner/CRMEventosTab'
import FeedbackTab from '@/components/owner/FeedbackTab'
import PropinasTab from '@/components/owner/PropinasTab'
import ProveedoresExternosTab from '@/components/owner/ProveedoresExternosTab'
import LeadsEventosTab from '@/components/owner/LeadsEventosTab'
import CalendarioEventosTab from '@/components/owner/CalendarioEventosTab'
import ProduccionTab from '@/components/owner/ProduccionTab'
import CobrosTab from '@/components/owner/CobrosTab'
