import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: [
        '/',
        '/registro',
        '/login',
        '/comanda-por-voz',
        '/hosteleria',
        '/eventos',
        '/espacios',
        '/restaurante-indio',
        '/restaurante-mediterraneo',
        '/grupo-multilocal',
        '/catering',
        '/tapas-bar',
        '/restaurantes',
        '/restaurantes/',
        '/r/',
        '/blog/',
        '/tienda/',
        '/descargar',
        '/privacidad',
        '/aviso-legal',
        '/cookies',
        '/terminos',
      ],
      disallow: [
        '/api/',
        '/edge',
        '/kds',
        '/owner',
        '/super',
        '/jefe',
        '/running',
        '/portal',
        '/asesoria',
        '/contable',
        '/almacen-central',
        '/asn/',
        '/q/',
        '/central',
        '/cocina',
        '/hub',
        '/bienvenida',
        '/onboarding',
        '/estado/',
        '/propuesta/',
        '/proveedor/',
        '/feedback/',
        '/propina/',
        '/contrato/',
        '/comercial',
        '/instalar',
        '/status',
        '/demo-storefront',
      ],
    },
    sitemap: 'https://www.iarest.es/sitemap.xml',
  }
}
