// @central/module-trading — lógica pura de análisis de inversión (Fase 1, paper).
export type * from './types.ts'
export { sma, ema, rsi, macd, atr, adx, indicadoresDe, regimenDe } from './indicadores.ts'
export { evaluarMomentum, evaluarReversion, evaluarValor, evaluarCatalizador, torneo } from './estrategias.ts'
export { superaConcentracion, esPromediarPerdedor, superaLimiteOps, earningsInminente } from './riesgo.ts'
export { dimensionar, abrir, aplicarStop, cerrar, pnlPosicion } from './paper.ts'
export { puntuarTesis, agregarStats } from './scoring.ts'
export type { Resultado, StatsEstrategia } from './scoring.ts'
export { rvol, tendenciaVolumen, volumenInusual, confirmaVolumen } from './volumen.ts'
export { infravalorada, pasaScreener, puntuarCandidato, rankearCantera } from './screener.ts'
export { dedupCandidatos, puntuarDescubrimiento, descubrir } from './descubrimiento.ts'
export { posicionRango52, tendenciaMedias, fuerzaRelativa } from './mercado.ts'
