// @central/module-trading — lógica pura de análisis de inversión (Fase 1, paper).
export type * from './types.ts'
export { sma, ema, rsi, macd, atr, adx, indicadoresDe, regimenDe } from './indicadores.ts'
export { evaluarMomentum, evaluarReversion, evaluarValor, evaluarCatalizador, torneo } from './estrategias.ts'
export { superaConcentracion, esPromediarPerdedor, superaLimiteOps, earningsInminente, bajoTendencia, factorFlojo } from './riesgo.ts'
export { dimensionar, abrir, aplicarStop, cerrar, pnlPosicion } from './paper.ts'
export { puntuarTesis, agregarStats, ajustesDeStats } from './scoring.ts'
export type { Resultado, StatsEstrategia } from './scoring.ts'
export { rvol, tendenciaVolumen, volumenInusual, confirmaVolumen } from './volumen.ts'
export { infravalorada, pasaScreener, puntuarCandidato, rankearCantera } from './screener.ts'
export { dedupCandidatos, puntuarDescubrimiento, descubrir } from './descubrimiento.ts'
export { posicionRango52, tendenciaMedias, fuerzaRelativa, rankearSectores, inclinacionSector, regimenMercado } from './mercado.ts'
export type { SectorRank } from './mercado.ts'
export { backtestSimbolo, backtestOOS } from './backtest.ts'
export type { TradeBT, ResultadoBacktest, OpcionesBacktest, ResultadoOOS } from './backtest.ts'
export { backtestCartera } from './cartera.ts'
export type { ResultadoCartera, OpcionesCartera } from './cartera.ts'
// Fase B — selección por factores (value + quality + momentum), Piotroski y fórmula mágica.
export { zscores, rankearFactores, momentum12_1 } from './factores.ts'
export type { MetricasFactor, PesosFactor, ScoreFactor } from './factores.ts'
export { piotroskiFScore } from './piotroski.ts'
export type { AnioFinanciero, Piotroski } from './piotroski.ts'
export { rankearMagicFormula } from './magicFormula.ts'
export type { EntradaMagic, RankMagic } from './magicFormula.ts'
