// @central/core-ai — núcleo IA compartido (casa de marcas).
// Adaptadores de proveedor PUROS e identity-agnostic (la config la inyecta la
// app). La POLÍTICA (fallback, timeouts, selección de modelo) vive en cada app.

export { cleanJSON } from './clean-json'
export { fetchAI, AiHttpError, isRateLimitError } from './http'
export type { AiRetryOptions } from './http'
export { nimText, nimChat, nimVision, nimChatTools } from './nim'
export type { NimChatMessage, NimChatOptions, NimToolMessage, NimToolCall, NimToolResult } from './nim'
export { groqText, groqChat, groqChatTools } from './groq'
export type { GroqConfig } from './groq'
export { cerebrasChat } from './cerebras'
export type { CerebrasConfig } from './cerebras'
export { groqTranscribe } from './stt'
export type { GroqSttConfig, AudioInput } from './stt'
export { moonshotChat } from './moonshot'
export type { MoonshotConfig } from './moonshot'
export { openrouterChat, openrouterChatEx, openrouterChatTools, openrouterSearchEx, openrouterVision, openrouterVisionEx } from './openrouter'
export type { OpenRouterConfig, OpenRouterChatOptions, OpenRouterChatResult, OpenRouterUsage } from './openrouter'
export { geminiEmbed } from './embeddings'
export type { GeminiEmbedConfig } from './embeddings'
export { geminiSearch, geminiVision, geminiChat } from './gemini'
export type { GeminiConfig } from './gemini'
export type { ImageInput, NimConfig } from './types'
export { aiComplete, aiCompleteConProveedor, aiTools, aiToolsConProveedor } from './client'
export type { AiCompleteResult, AiToolsResult, ProveedorTexto } from './client'
export { gatewayChat, gatewaySearch, gatewayVision, gatewayTools, gatewayVideo } from './gateway'
export type { GatewayConfig, GatewayVideoOpts } from './gateway'
export { falTextToVideo, falImageToVideo } from './fal'
export type { FalConfig, FalVideoOpts } from './fal'
