export {
  POLIZA_ESTADOS_VIGENTES,
  esEstadoVigente,
  vigenciaPoliza,
  explicarVigenciaPendiente,
  type Vigencia,
  type EstadoPolizaVigente,
} from './vigencia.ts'

export {
  DIAS_PREAVISO_TOMADOR,
  DIAS_PREAVISO_ASEGURADOR,
  DIAS_HORIZONTE_RENOVACION,
  diasHastaVencimiento,
  fechaLimiteOposicion,
  fechaLimiteComunicacionAseguradora,
  comunicacionEnPlazo,
  urgenciaRenovacion,
  etiquetaUrgencia,
  primaReferencia,
  primaEnRiesgo,
  type UrgenciaRenovacion,
} from './vencimientos.ts'

export {
  objetoAsegurado,
  pareceMatricula,
  type ObjetoAsegurado,
  type EstadoObjeto,
  type EntradaObjeto,
} from './objeto.ts'

export {
  saludIngesta,
  detalleSalud,
  DIAS_CUARENTENA_RECIENTE,
  type EstadoIngesta,
  type SaludIngesta,
  type EntradaSalud,
  type FicheroEnCuarentena,
} from './ingesta.ts'
export {
  MARCADORES_SIN_DATO,
  CAMPOS_PERSONALES,
  autoLeidoVacio,
  normalizarAutoLeido,
  seLeyoAlgo as seLeyoAlgoAuto,
  camposLeidos,
} from './documento-auto.ts'
export type { AutoLeido } from './documento-auto.ts'

export { importeEiac, sumarImportesEiac } from './importe-eiac.ts'
export {
  interpretarCapital,
  extraerDetalleCobertura,
  type CapitalCobertura,
  type DetalleCobertura,
  type LimiteCobertura,
  type FranquiciaCobertura,
  type PrimaCobertura,
} from './cobertura-detalle.ts'
export {
  resumirRecibos,
  estadoCobro,
  explicarCobro,
  type ReciboCrudo,
  type ReciboResumen,
  type RecibosPoliza,
  type EstadoCobro,
} from './recibos.ts'
export {
  MINIMO_TEXTO,
  planBusqueda,
  avisoDireccion,
  explicarVacio,
  normalizarDireccion,
  direccionCoincide,
  type Criterio,
  type TipoCriterio,
  type PlanBusqueda,
  type Aviso,
  type Cobertura,
} from './busqueda.ts'
export {
  DIAS_SUSPENSION,
  DIAS_EXTINCION,
  retencion,
  resumirRetencion,
  type EstadoRetencion,
  type Retencion,
  type ResumenRetencion,
} from './retencion.ts'
export {
  MESES_CARTERA_VIVA,
  vitalidadFicha,
  etiquetaVitalidad,
  explicarVitalidad,
  avisoHermanas,
  type Vitalidad,
  type SenalesFicha,
  type Hermana,
  type AvisoHermanas,
} from './vitalidad.ts'
export {
  etiquetaRol,
  contactoEfectivo,
  filasIntervinientes,
  type IntervinienteFicha,
  type ContactoEfectivo,
  type FilasIntervinientes,
} from './intervinientes.ts'
export {
  FRACCIONES,
  etiquetaFraccionamiento,
  etiquetaFormaPago,
  recargoFraccionamiento,
  ventanaAnulacion,
  type ReciboCiclo,
  type RecargoFraccionamiento,
} from './pago.ts'
export {
  TIPOS_DOCUMENTO,
  MIMES_DOCUMENTO,
  MAX_BYTES_DOCUMENTO,
  NECESARIOS_EMISION_AUTO,
  etiquetaTipoDocumento,
  etiquetaEstadoDocumento,
  tipoDocumento,
  estadoDocumento,
  revisarDocumento,
  resumenDocumentos,
  documentosQueFaltan,
  type TipoDocumento,
  type EstadoDocumento,
  type DocumentoResumen,
  type ResumenDocumentos,
} from './documentos.ts'
export {
  retarificabilidad,
  RIESGO_HOGAR_MINIMO,
  numeroPositivo,
  anioPlausible,
  cpValido,
  type Retarificabilidad,
  type RamoRetarificable,
  type EntradaRetarificable,
} from './retarificable.ts'
export {
  ETIQUETAS_TELEFONO,
  ETIQUETAS_EMAIL,
  CAMPOS_IDENTIDAD,
  CAMPOS_LIBRES,
  ETIQUETA_CAMPO,
  MOTIVO_DOCUMENTO_REQUERIDO,
  etiquetaContacto,
  normalizarTelefono,
  normalizarEmail,
  normalizarContacto,
  normalizarDni,
  etiquetasIdentidad,
  enmascararDni,
  normalizarFechaNacimiento,
  normalizarNombre,
  normalizarCp,
  provinciaPorCp,
  revisarEdicion,
  documentoAcredita,
  documentosAcreditativos,
  textoHistorialEdicion,
  revisarAlta,
  coincidenciaBloquea,
  FUENTES_ORIGEN,
  FUENTES_CANAL,
  ETIQUETA_FUENTE,
  TIPOS_HISTORIAL,
  esFuenteCanal,
  fuenteOrigen,
  tipoHistorial,
  tipoHistorialAlta,
  textoHistorialAlta,
  type FuenteOrigen,
  type TipoHistorial,
  type Revisado,
  type TipoContacto,
  type ContactoCliente,
  type TipoPersona,
  type EtiquetasIdentidad,
  type CampoIdentidad,
  type CampoLibre,
  type EdicionCliente,
  type IdentidadRevisada,
  type EdicionRevisada,
  type AltaCliente,
  type AltaRevisada,
  type Coincidencia,
} from './cliente-edicion.ts'
export {
  TIPOS_RELACION,
  GRUPOS_RELACION,
  tipoRelacion,
  tipoInverso,
  relacionesDeFicha,
  clientesVisiblesPara,
  explicarAutorizacion,
  type TipoRelacion,
  type RelacionFila,
  type RelacionFicha,
} from './relaciones.ts'
export {
  estadoCliente,
  DIAS_PRESUPUESTO_VIVO,
  type EstadoCliente,
  type SenalesCliente,
  type EstadoClienteDerivado,
} from './estado-cliente.ts'
export {
  normalizarNumeroPoliza,
  polizasDuplicadas,
  type PolizaParaDuplicados,
  type GrupoDuplicado,
} from './duplicados.ts'
export {
  ESTADOS_SINIESTRO,
  TRANSICIONES_SINIESTRO,
  TIPOS_SINIESTRO,
  GRAVEDADES_SINIESTRO,
  DIAS_COMUNICACION_LCS,
  CAMPOS_SEGUIMIENTO_CIMA,
  CAMPOS_SEGUIMIENTO_PROPIO,
  esEstadoSiniestro,
  esTipoSiniestro,
  etiquetaEstadoSiniestro,
  etiquetaTipoSiniestro,
  revisarTransicion,
  plazoComunicacion,
  revisarApertura,
  revisarSeguimiento,
  anadirNota,
  textoHistorialSiniestro,
  type EstadoSiniestro,
  type OrigenSiniestro,
  type ClaveTipoSiniestro,
  type PlazoComunicacion,
  type AperturaSiniestro,
  type AperturaRevisada,
  type SeguimientoSiniestro,
  type SeguimientoRevisado,
} from './siniestros.ts'
export {
  evolucionPrima,
  etiquetaVeredictoPrima,
  inicioCiclo,
  UMBRAL_IGUAL_PCT,
  UMBRAL_SUBIDA_GENERAL_PCT,
  type ReciboEvolucion,
  type SiniestroEvolucion,
  type Anualidad,
  type VeredictoPrima,
  type EvolucionPrima,
} from './prima-evolucion.ts'
export {
  prepararPolizaEmitida,
  emparejarConCima,
  conciliarConCima,
  sanearPrima,
  TIPOS_SEGURO,
  PRIMA_ANUAL_MAX,
  MARGEN_FECHA_INICIO_DIAS,
  type CompaniaDgs,
  type ProyectoEmitido,
  type PolizaEmitida,
  type PreparacionEmision,
  type PolizaCandidata,
  type PolizaCima,
  type Emparejamiento,
  type NuestraPoliza,
  type CimaPoliza,
  type Conciliacion,
} from './emision.ts'
export {
  ladoDeGarantia,
  capitalAsegurado,
  capitalesHogar,
  eurDeCapital,
  GARANTIAS_MINIMAS_CONSENSO,
  type LadoRiesgo,
  type CoberturaLeible,
  type CapitalAsegurado,
  type CapitalesHogar,
} from './garantias.ts'
